backend:
  name: github
  repo: willysanky/[your-repo-name] # 👈 Replace with your actual GitHub repo
  branch: main
  site_domain: subsaharanconference.netlify.app

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "speakers"
    label: "Speakers"
    folder: "content/speakers"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
