backend:
  name: github
  repo: willysanky/subsaharanconference
  branch: main
  site_domain: subsaharanconference.netlify.app

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "speakers"
    label: "Speakers"
    folder: "content/speakers"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Photo", name: "photo", widget: "image" }
      - { label: "Bio", name: "bio", widget: "text" }
